export interface IBook {
  name: string,
  country: string,
  authors: string[],
  characters: string[],
  isbn: string,
  mediaType: string,
  numberOfPages: number,
  povCharacters: string[],
  publisher: string,
  released: string,
  url: string,
}
export interface ICharacter {
  name: string,
  general: string,
  culture?: string,
  born?: string | number,
  died?: string | number,
  titles?: string[],
  aliases?: string[],
  father?: string,
  mother?: string,
  spouse: string,
  allegiances: string[],
  books: string[],
  povBooks?: any[],
  tvSevies?: string[],
  playedBy?: string[],
}
